# Lab 5 — Cleaning and Transforming Data in Pandas

**Course:** Python for AI & Data  
**Analyst:** *(your name)*  
**Date:** *(today's date)*

---

## The PaperLane Scenario

PaperLane's sales team has been logging orders manually across spreadsheets. The data has never been cleaned. Before any analysis can happen, it needs to be fixed.

Your job: take the raw order export and produce a clean, analysis-ready dataset.

Work from top to bottom. Run every cell as you go.

---
## Task 1 — Load and First Look

Load the raw data from `data/raw/paperlane_orders.csv` into a DataFrame.

After loading:
- Display the first 5 rows with `head()`
- Print the shape (rows, columns)
- Print the column names

In [75]:
import pandas as pd
from pathlib import Path

# Define paths
RAW = Path("..") / "data" / "raw"
PROCESSED = Path("..") / ("data") / "processed"

# Load the raw data
df = pd.read_csv(RAW / "paperlane_orders.csv")

# Display first 5 rows
df.head(5)

# Print shape and column names
#df.shape

,order_id,order_date,customer,region,product,quantity,unit_price,channel,status
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Online,Complete
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,In-Store,Complete
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Online,Complete
3,1004,2026-01-06,Ava,East,Backpack,1,NaN,Online,Returned
4,1005,2026-01-07,Priya,South,Pen,5,1.25,In-Store,Complete

In [47]:
df.shape

(21, 9)

In [76]:
df.columns.tolist()

['order_id',
 'order_date',
 'customer',
 'region',
 'product',
 'quantity',
 'unit_price',
 'channel',
 'status']

---
## Task 2 — Structured Inspection

Before touching the data, build a complete picture of its quality issues.

Use all of the following:
- `df.info()` — types and null counts
- `df.isna().sum()` — missing values per column
- `df.duplicated().sum()` — duplicate rows
- `df["status"].value_counts()` — spot inconsistent values
- `df["region"].value_counts()` — spot whitespace issues

Then, in the markdown cell below the code, **document every issue you found** before making any changes.

In [77]:
# Run all inspection methods here
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    21 non-null     int64
 1   order_date  21 non-null     object
 2   customer    21 non-null     object
 3   region      19 non-null     object
 4   product     21 non-null     object
 5   quantity    21 non-null     int64
 6   unit_price  19 non-null     float64
 7   channel     21 non-null     object
 8   status      21 non-null     object
dtypes: float64(1), int64(2), object(6)
memory usage: 1.6+ KB

In [78]:
df.isna().sum()

order_id      0
order_date    0
customer      0
region        2
product       0
quantity      0
unit_price    2
channel       0
status        0
dtype: int64

In [79]:
df.duplicated().sum()

np.int64(1)

In [80]:
df["status"].value_counts()

status
Complete    16
COMPLETE     2
Returned     1
complete     1
returned     1
Name: count, dtype: int64

In [81]:
df["region"].value_counts()

region
East        5
Midwest     4
South       3
West        3
 West       2
 East       1
Midwest     1
Name: count, dtype: int64

In [82]:
df

,order_id,order_date,customer,region,product,quantity,unit_price,channel,status
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Online,Complete
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,In-Store,Complete
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Online,Complete
3,1004,2026-01-06,Ava,East,Backpack,1,NaN,Online,Returned
4,1005,2026-01-07,Priya,South,Pen,5,1.25,In-Store,Complete
5,1006,2026-01-07,Noah,West,Marker,3,2.50,In-Store,COMPLETE
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Online,Complete
7,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Online,Complete
8,1008,2026-01-08,Ava,NaN,Marker,4,2.50,In-Store,Complete
9,1009,01/09/2026,Priya,South,Notebook,2,8.99,Online,Complete
10,1010,2026-01-09,Jordan,East,Pen,8,1.25,Online,complete
11,1011,2026-01-10,Miles,Midwest,Binder,3,5.50,In-Store,Complete
12,1012,2026-01-10,Sofia,West,Backpack,1,39.00,Online,Complete
13,1013,2026-01-11,Ava,East,Binder,2,NaN,In-Store,Complete
14,1014,2026-01-11,Jordan,East,Marker,6,2.50,Online,Complete
15,1015,2026-01-12,Noah,West,Pen,4,1.25,In-Store,returned
16,1016,2026-01-12,Sofia,West,Binder,1,5.50,Online,Complete
17,1017,2026-01-13,Priya,South,Backpack,1,39.00,In-Store,Complete
18,1018,2026-01-13,Miles,Midwest,Notebook,3,8.99,Online,Complete
19,1019,2026-01-14,Ava,East,Pen,12,1.25,In-Store,COMPLETE
20,1020,01/14/2026,Jordan,NaN,Binder,2,5.50,Online,Complete

In [83]:
df["channel"].value_counts()

channel
Online      12
In-Store     9
Name: count, dtype: int64

### Data Quality Issues Found

*(Replace this text with your findings. 
we have 1 dupllicated row 6/7 
we have Nan for region on row 8 and row 20
unit price is NaN on row 13 
there are multiple different ways Complete is spelt 



List every issue, which column it affects, and how many rows are impacted.)*
Duplication 1 row status as complete is

---
## Task 3 — Remove Duplicates

Remove any duplicate rows from the DataFrame.

Print the shape before and after to confirm how many rows were removed.

In [84]:
# Print shape before

print("Before:", df.shape)


# Remove duplicates
df = df.drop_duplicates()

# Print shape after
print("After:", df.shape)

Before: (21, 9)
After: (20, 9)

---
## Task 4 — Handle Missing Values

Two columns have missing values. Handle each one.

For each column:
1. Choose a strategy (fill with a value, fill with a statistic, or drop)
2. Apply it
3. In the markdown cell below, explain why you chose that strategy

After handling both, verify with `df.isna().sum()` — all values should be 0.

In [85]:
df.isna().sum()

order_id      0
order_date    0
customer      0
region        2
product       0
quantity      0
unit_price    2
channel       0
status        0
dtype: int64

In [86]:
# Handle missing values
#will replace numeric missing values for unit_price with the median
df= df.dropna(subset=["unit_price"])
#will replace nan region with unknown
df = df.dropna(subset=["region"])


# Verify all missing values are resolved
df.isna().sum()

order_id      0
order_date    0
customer      0
region        0
product       0
quantity      0
unit_price    0
channel       0
status        0
dtype: int64

In [87]:
df

,order_id,order_date,customer,region,product,quantity,unit_price,channel,status
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Online,Complete
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,In-Store,Complete
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Online,Complete
4,1005,2026-01-07,Priya,South,Pen,5,1.25,In-Store,Complete
5,1006,2026-01-07,Noah,West,Marker,3,2.50,In-Store,COMPLETE
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Online,Complete
9,1009,01/09/2026,Priya,South,Notebook,2,8.99,Online,Complete
10,1010,2026-01-09,Jordan,East,Pen,8,1.25,Online,complete
11,1011,2026-01-10,Miles,Midwest,Binder,3,5.50,In-Store,Complete
12,1012,2026-01-10,Sofia,West,Backpack,1,39.00,Online,Complete
14,1014,2026-01-11,Jordan,East,Marker,6,2.50,Online,Complete
15,1015,2026-01-12,Noah,West,Pen,4,1.25,In-Store,returned
16,1016,2026-01-12,Sofia,West,Binder,1,5.50,Online,Complete
17,1017,2026-01-13,Priya,South,Backpack,1,39.00,In-Store,Complete
18,1018,2026-01-13,Miles,Midwest,Notebook,3,8.99,Online,Complete
19,1019,2026-01-14,Ava,East,Pen,12,1.25,In-Store,COMPLETE

### Cleaning Decisions

*(Explain your strategy for each column here.)*

---
## Task 5 — Standardise Text Columns

Fix inconsistent casing and whitespace in `status`, `region`, and `channel`.

Use `str.strip()` to remove whitespace and `str.title()` to normalise casing.

After each fix, run `value_counts()` to confirm the column is now consistent.

In [88]:
# Standardise status
df["status"] = df["status"].str.strip().str.title()

# takes teh space out 

# Standardise region
df["region"] = df["region"].str.strip()

# Standardise channel
df["status"] = df["status"].str.strip().str.title()
#need to standardize date 1 is sticking out that is not liek teh others 
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')
df = df.dropna(subset=['order_date'])
# Verify each column
df["status"].value_counts()
df["region"].value_counts()
df["channel"].value_counts()

channel
Online      8
In-Store    7
Name: count, dtype: int64

In [89]:
df["status"].value_counts()

status
Complete    14
Returned     1
Name: count, dtype: int64

In [90]:
df["region"].value_counts()

region
West       5
East       4
Midwest    4
South      2
Name: count, dtype: int64

In [91]:
df

,order_id,order_date,customer,region,product,quantity,unit_price,channel,status
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Online,Complete
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,In-Store,Complete
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Online,Complete
4,1005,2026-01-07,Priya,South,Pen,5,1.25,In-Store,Complete
5,1006,2026-01-07,Noah,West,Marker,3,2.50,In-Store,Complete
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Online,Complete
10,1010,2026-01-09,Jordan,East,Pen,8,1.25,Online,Complete
11,1011,2026-01-10,Miles,Midwest,Binder,3,5.50,In-Store,Complete
12,1012,2026-01-10,Sofia,West,Backpack,1,39.00,Online,Complete
14,1014,2026-01-11,Jordan,East,Marker,6,2.50,Online,Complete
15,1015,2026-01-12,Noah,West,Pen,4,1.25,In-Store,Returned
16,1016,2026-01-12,Sofia,West,Binder,1,5.50,Online,Complete
17,1017,2026-01-13,Priya,South,Backpack,1,39.00,In-Store,Complete
18,1018,2026-01-13,Miles,Midwest,Notebook,3,8.99,Online,Complete
19,1019,2026-01-14,Ava,East,Pen,12,1.25,In-Store,Complete

---
## Task 6 — Convert the Date Column

The `order_date` column currently has `object` dtype and contains some non-standard date formats.

Convert it to a proper `datetime` type using `pd.to_datetime()`.

After converting, confirm the dtype has changed by printing `df["order_date"].dtype`.

In [92]:
# Convert order_date to datetime

df["order_date"] = pd.to_datetime(df["order_date"], dayfirst=False)
print(df["order_date"].dtype) 
#df['order_date'] = pd.to_datetime(df['order_date'])
# Confirm the dtype
#df
df.info()

datetime64[ns]
<class 'pandas.core.frame.DataFrame'>
Index: 15 entries, 0 to 19
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    15 non-null     int64
 1   order_date  15 non-null     datetime64[ns]
 2   customer    15 non-null     object
 3   region      15 non-null     object
 4   product     15 non-null     object
 5   quantity    15 non-null     int64
 6   unit_price  15 non-null     float64
 7   channel     15 non-null     object
 8   status      15 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(2), object(5)
memory usage: 1.2+ KB

C:\Users\info\AppData\Local\Temp\ipykernel_17680\1425210886.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["order_date"] = pd.to_datetime(df["order_date"], dayfirst=False)

---
## Task 7 — Create Derived Columns

Add two new columns to the DataFrame:

1. **`revenue`** = `quantity` × `unit_price`
2. **`order_month`** = the month number extracted from `order_date` (hint: use `.dt.month`)

Display a sample of the relevant columns to confirm.

In [93]:
# Create revenue column
#we have to calculate this using the surrcrent rows
df["revenue"] = df["quantity"] * df["unit_price"]

# Create order_month column
#since teh dat eis already in teh fiekd we have to take teh month from it 
df["order_month"] = df["order_date"].dt.month
# Display a sample

C:\Users\info\AppData\Local\Temp\ipykernel_17680\23340636.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["revenue"] = df["quantity"] * df["unit_price"]
C:\Users\info\AppData\Local\Temp\ipykernel_17680\23340636.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["order_month"] = df["order_date"].dt.month

In [94]:
df

,order_id,order_date,customer,region,product,quantity,unit_price,channel,status,revenue,order_month
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Online,Complete,17.98,1
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,In-Store,Complete,12.50,1
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Online,Complete,8.99,1
4,1005,2026-01-07,Priya,South,Pen,5,1.25,In-Store,Complete,6.25,1
5,1006,2026-01-07,Noah,West,Marker,3,2.50,In-Store,Complete,7.50,1
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Online,Complete,78.00,1
10,1010,2026-01-09,Jordan,East,Pen,8,1.25,Online,Complete,10.00,1
11,1011,2026-01-10,Miles,Midwest,Binder,3,5.50,In-Store,Complete,16.50,1
12,1012,2026-01-10,Sofia,West,Backpack,1,39.00,Online,Complete,39.00,1
14,1014,2026-01-11,Jordan,East,Marker,6,2.50,Online,Complete,15.00,1
15,1015,2026-01-12,Noah,West,Pen,4,1.25,In-Store,Returned,5.00,1
16,1016,2026-01-12,Sofia,West,Binder,1,5.50,Online,Complete,5.50,1
17,1017,2026-01-13,Priya,South,Backpack,1,39.00,In-Store,Complete,39.00,1
18,1018,2026-01-13,Miles,Midwest,Notebook,3,8.99,Online,Complete,26.97,1
19,1019,2026-01-14,Ava,East,Pen,12,1.25,In-Store,Complete,15.00,1

---
## Task 8 — Filter and Sort

Create a new DataFrame called `df_complete` containing only orders with `status == "Complete"`.

- Use `.copy()` when creating the filtered DataFrame
- Sort by `revenue` descending
- Print how many complete orders there are out of the total
- Display the top 5 rows

In [95]:
# Filter to complete orders only
df_complete = df[df["status"] == "Complete"].copy()

# Sort by revenue descending
df_complete = df_complete.sort_values(by="revenue",ascending=False)

# Print count and display top 5
print(f"Complete orders: {len(df_complete)} of {len(df)} total")

df_complete.head(5)

Complete orders: 14 of 15 total

,order_id,order_date,customer,region,product,quantity,unit_price,channel,status,revenue,order_month
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Online,Complete,78.00,1
12,1012,2026-01-10,Sofia,West,Backpack,1,39.00,Online,Complete,39.00,1
17,1017,2026-01-13,Priya,South,Backpack,1,39.00,In-Store,Complete,39.00,1
18,1018,2026-01-13,Miles,Midwest,Notebook,3,8.99,Online,Complete,26.97,1
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Online,Complete,17.98,1

In [96]:
df_complete

,order_id,order_date,customer,region,product,quantity,unit_price,channel,status,revenue,order_month
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Online,Complete,78.00,1
12,1012,2026-01-10,Sofia,West,Backpack,1,39.00,Online,Complete,39.00,1
17,1017,2026-01-13,Priya,South,Backpack,1,39.00,In-Store,Complete,39.00,1
18,1018,2026-01-13,Miles,Midwest,Notebook,3,8.99,Online,Complete,26.97,1
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Online,Complete,17.98,1
11,1011,2026-01-10,Miles,Midwest,Binder,3,5.50,In-Store,Complete,16.50,1
14,1014,2026-01-11,Jordan,East,Marker,6,2.50,Online,Complete,15.00,1
19,1019,2026-01-14,Ava,East,Pen,12,1.25,In-Store,Complete,15.00,1
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,In-Store,Complete,12.50,1
10,1010,2026-01-09,Jordan,East,Pen,8,1.25,Online,Complete,10.00,1
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Online,Complete,8.99,1
5,1006,2026-01-07,Noah,West,Marker,3,2.50,In-Store,Complete,7.50,1
4,1005,2026-01-07,Priya,South,Pen,5,1.25,In-Store,Complete,6.25,1
16,1016,2026-01-12,Sofia,West,Binder,1,5.50,Online,Complete,5.50,1

In [97]:
df

,order_id,order_date,customer,region,product,quantity,unit_price,channel,status,revenue,order_month
0,1001,2026-01-05,Ava,East,Notebook,2,8.99,Online,Complete,17.98,1
1,1002,2026-01-05,Miles,Midwest,Pen,10,1.25,In-Store,Complete,12.50,1
2,1003,2026-01-06,Noah,West,Notebook,1,8.99,Online,Complete,8.99,1
4,1005,2026-01-07,Priya,South,Pen,5,1.25,In-Store,Complete,6.25,1
5,1006,2026-01-07,Noah,West,Marker,3,2.50,In-Store,Complete,7.50,1
6,1007,2026-01-08,Miles,Midwest,Backpack,2,39.00,Online,Complete,78.00,1
10,1010,2026-01-09,Jordan,East,Pen,8,1.25,Online,Complete,10.00,1
11,1011,2026-01-10,Miles,Midwest,Binder,3,5.50,In-Store,Complete,16.50,1
12,1012,2026-01-10,Sofia,West,Backpack,1,39.00,Online,Complete,39.00,1
14,1014,2026-01-11,Jordan,East,Marker,6,2.50,Online,Complete,15.00,1
15,1015,2026-01-12,Noah,West,Pen,4,1.25,In-Store,Returned,5.00,1
16,1016,2026-01-12,Sofia,West,Binder,1,5.50,Online,Complete,5.50,1
17,1017,2026-01-13,Priya,South,Backpack,1,39.00,In-Store,Complete,39.00,1
18,1018,2026-01-13,Miles,Midwest,Notebook,3,8.99,Online,Complete,26.97,1
19,1019,2026-01-14,Ava,East,Pen,12,1.25,In-Store,Complete,15.00,1

---
## Task 9 — Save Cleaned Data

Save two files to `data/processed/`:

1. The full cleaned DataFrame → `paperlane_orders_clean.csv`
2. The complete-orders DataFrame → `paperlane_orders_complete.csv`

Use `index=False` in `to_csv()`. Create the `processed/` folder if it doesn't exist.

After saving, verify both files exist using `Path.exists()`.

In [98]:
# Create processed directory
PROCESSED.mkdir(parents=True, exist_ok=True)

# Save full cleaned DataFrame

df.to_csv(PROCESSED / "paperlane_orders_clean.csv", index=False)

# Save complete-orders DataFrame
df_complete.to_csv(PROCESSED / "paperlane_orders_complete.csv", index=False)

# Verify both files exist
clean_exists = (PROCESSED / "paperlane_orders_clean.csv").exists()
complete_exists = (PROCESSED / "paperlane_orders_complete.csv").exists()

print(f"Cleaned file saved: {clean_exists}")
print(f"Complete file saved: {complete_exists}")

Cleaned file saved: True
Complete file saved: True

---
## ⭐ Optional Advanced Tasks

### Optional 1 — Revenue by Region
Group `df_complete` by `region` and calculate total revenue, number of orders, and average order value per region. Display as a DataFrame sorted by total revenue descending.

### Optional 2 — Revenue by Channel
Do the same grouping but by `channel`. Does Online or In-Store drive more revenue for PaperLane?

### Optional 3 — Pivot Table
Build a pivot table showing total revenue by `region` (rows) and `product` (columns). Use `pd.pivot_table()`. Fill missing combinations with 0.

In [ ]:
# Optional tasks — work here